import { Share2, FileText, MessageCircle, X } from 'lucide-react';
import { useState } from 'react';

export default function ExportShare({ scan, onClose }) {
  const [showReport, setShowReport] = useState(false);

  if (!scan) return null;

  const buildShareText = () => {
    return `🌱 *FarmBuddy Scan Report*
━━━━━━━━━━━━━━━
📋 *${scan.identity}* (${scan.type})
🔬 Diagnosis: ${scan.diagnosis}
⚠️ Severity: ${scan.severity}
💚 Health: ${scan.healthPercentage}%
🕐 Urgency: ${scan.urgency || 'N/A'}
📍 Affected Area: ${scan.affectedArea || 'N/A'}
📅 Date: ${scan.date}

📝 *Action Plan:*
${scan.actionPlan || 'N/A'}

⚡ *Immediate Care:*
${scan.immediateCare || 'N/A'}
━━━━━━━━━━━━━━━
_Generated by FarmBuddy AI_ 🤖`;
  };

  const shareWhatsApp = () => {
    const text = encodeURIComponent(buildShareText());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const shareNative = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `FarmBuddy Report: ${scan.identity}`,
          text: buildShareText(),
        });
      } catch (err) {
        if (err.name !== 'AbortError') console.error('Share failed:', err);
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(buildShareText());
      alert('Report copied to clipboard!');
    }
  };

  const printReport = () => {
    setShowReport(true);
    setTimeout(() => {
      window.print();
      setShowReport(false);
    }, 300);
  };

  return (
    <>
      {/* Share Buttons */}
      <div className="flex gap-2 mt-4">
        <button onClick={shareWhatsApp} className="flex-1 bg-[#25D366]/10 border border-[#25D366]/30 text-[#25D366] py-3 rounded-xl text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2 active:scale-95 transition-transform">
          <MessageCircle className="w-4 h-4" /> WhatsApp
        </button>
        <button onClick={printReport} className="flex-1 bg-charcoal/5 dark:bg-white/10 border border-sage/20 text-charcoal dark:text-white py-3 rounded-xl text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2 active:scale-95 transition-transform">
          <FileText className="w-4 h-4" /> PDF
        </button>
        <button onClick={shareNative} className="flex-1 bg-teal/10 border border-teal/20 text-teal py-3 rounded-xl text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2 active:scale-95 transition-transform">
          <Share2 className="w-4 h-4" /> Share
        </button>
      </div>

      {/* Print-only Report */}
      {showReport && (
        <div className="fixed inset-0 bg-white z-[999] p-8 print-report overflow-auto">
          <style>{`@media print { body * { visibility: hidden; } .print-report, .print-report * { visibility: visible; } .print-report { position: absolute; left: 0; top: 0; width: 100%; } }`}</style>
          <div className="max-w-2xl mx-auto">
            <div className="flex items-center gap-3 mb-8 border-b-2 border-charcoal pb-4">
              <span className="text-3xl">🌱</span>
              <div>
                <h1 className="text-2xl font-black text-charcoal">FarmBuddy</h1>
                <p className="text-sage text-sm font-bold">AI Diagnostic Report</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-6">
              <div className="bg-offWhite rounded-xl p-4">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold">Subject</p>
                <p className="text-charcoal font-black text-lg">{scan.identity}</p>
              </div>
              <div className="bg-offWhite rounded-xl p-4">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold">Type</p>
                <p className="text-charcoal font-black text-lg">{scan.type}</p>
              </div>
              <div className="bg-offWhite rounded-xl p-4">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold">Health Score</p>
                <p className="text-teal font-black text-lg">{scan.healthPercentage}%</p>
              </div>
              <div className="bg-offWhite rounded-xl p-4">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold">Date</p>
                <p className="text-charcoal font-black text-lg">{scan.date}</p>
              </div>
            </div>

            <div className="mb-4 p-4 border-l-4 border-coralRed bg-coralRed/5 rounded-r-xl" style={{ borderLeftColor: scan.severity === 'Healthy' ? '#2ec4b6' : '#e63946' }}>
              <p className="text-[10px] text-sage uppercase tracking-widest font-bold mb-1">Diagnosis</p>
              <p className="font-bold text-charcoal">{scan.diagnosis}</p>
              <p className="text-sm mt-1 text-sage">Severity: <span className="font-bold text-charcoal">{scan.severity}</span> | Urgency: <span className="font-bold text-charcoal">{scan.urgency || 'N/A'}</span></p>
            </div>

            {scan.affectedArea && (
              <div className="mb-4 p-4 bg-offWhite rounded-xl">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold mb-1">Affected Area</p>
                <p className="font-bold text-charcoal text-sm">{scan.affectedArea}</p>
              </div>
            )}

            {scan.possibleConditions?.length > 0 && (
              <div className="mb-4 p-4 bg-offWhite rounded-xl">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold mb-2">Possible Conditions</p>
                {scan.possibleConditions.map((c, i) => (
                  <p key={i} className="text-sm font-semibold text-charcoal ml-4">{i + 1}. {c}</p>
                ))}
              </div>
            )}

            {scan.immediateCare && (
              <div className="mb-4 p-4 bg-amber-50 rounded-xl border-l-4 border-amber-500">
                <p className="text-[10px] text-sage uppercase tracking-widest font-bold mb-1">⚡ Immediate Care</p>
                <p className="text-sm font-semibold text-charcoal">{scan.immediateCare}</p>
              </div>
            )}

            <div className="mb-8 p-4 bg-offWhite rounded-xl">
              <p className="text-[10px] text-sage uppercase tracking-widest font-bold mb-2">Action Plan</p>
              <p className="text-sm font-semibold text-charcoal whitespace-pre-wrap">{scan.actionPlan}</p>
            </div>

            <p className="text-center text-sage text-xs font-bold">Generated by FarmBuddy AI • {new Date().toLocaleDateString()}</p>
          </div>
        </div>
      )}
    </>
  );
}
